ALTER TABLE "budget_carry_forward" ALTER COLUMN "amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "budget_entries" ALTER COLUMN "planned_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "budget_entries" ALTER COLUMN "actual_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "business_profile" ALTER COLUMN "invoice_start_number" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "business_profile" ALTER COLUMN "invoice_start_number" SET DEFAULT 1;--> statement-breakpoint
ALTER TABLE "capital_gains" ALTER COLUMN "purchase_price" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "capital_gains" ALTER COLUMN "sale_price" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "capital_gains" ALTER COLUMN "capital_gain" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "capital_gains" ALTER COLUMN "exemption_applied" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "capital_gains" ALTER COLUMN "taxable_gain" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "capital_gains" ALTER COLUMN "tax_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "carryforward_balances" ALTER COLUMN "amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "chit_fund_installments" ALTER COLUMN "installment_paid" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "chit_fund_installments" ALTER COLUMN "dividend_received" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "chit_fund_installments" ALTER COLUMN "net_outgo" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "chit_funds" ALTER COLUMN "chit_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "chit_funds" ALTER COLUMN "monthly_installment" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "chit_funds" ALTER COLUMN "document_charges_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "chit_funds" ALTER COLUMN "total_paid" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "chit_funds" ALTER COLUMN "total_dividends" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "chit_funds" ALTER COLUMN "net_contribution" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "chit_funds" ALTER COLUMN "win_amount_received" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "credit_card_expenses" ALTER COLUMN "amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "credit_card_expenses" ALTER COLUMN "paid_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "financial_goals" ALTER COLUMN "target_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "financial_goals" ALTER COLUMN "current_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "fixed_deposits" ALTER COLUMN "principal_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "fixed_deposits" ALTER COLUMN "maturity_amount_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "future_savings_plan" ALTER COLUMN "lump_sum_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "future_savings_plan" ALTER COLUMN "monthly_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "gold_holdings" ALTER COLUMN "current_price" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "gold_holdings" ALTER COLUMN "total_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "gold_holdings" ALTER COLUMN "purchase_price" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "gold_holdings" ALTER COLUMN "purchase_price_per_gram" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "gold_holdings" ALTER COLUMN "current_rate_per_gram" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "gold_holdings" ALTER COLUMN "total_investment" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "gold_holdings" ALTER COLUMN "current_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "gold_holdings" ALTER COLUMN "gain_loss" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "holdings" ALTER COLUMN "average_price" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "holdings" ALTER COLUMN "current_price" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "holdings" ALTER COLUMN "total_investment" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "holdings" ALTER COLUMN "current_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "holdings" ALTER COLUMN "gain_loss" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "income_tax_paid" ALTER COLUMN "amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "insurance_policies" ALTER COLUMN "sum_assured" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "insurance_policies" ALTER COLUMN "maturity_benefit" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "insurance_policies" ALTER COLUMN "premium_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "insurance_policies" ALTER COLUMN "investment_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "insurance_policies" ALTER COLUMN "investment_gain_loss" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "insurance_policies" ALTER COLUMN "annuity_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "investment_transactions" ALTER COLUMN "price_per_unit" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "investment_transactions" ALTER COLUMN "amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "investment_transactions" ALTER COLUMN "brokerage_charges" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "investment_transactions" ALTER COLUMN "taxes_and_charges" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "investment_transactions" ALTER COLUMN "total_cost" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoice_items" ALTER COLUMN "unit_price" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoice_items" ALTER COLUMN "discount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoice_items" ALTER COLUMN "taxable_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoice_items" ALTER COLUMN "cgst_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoice_items" ALTER COLUMN "sgst_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoice_items" ALTER COLUMN "igst_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoice_items" ALTER COLUMN "total_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoices" ALTER COLUMN "taxable_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoices" ALTER COLUMN "cgst_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoices" ALTER COLUMN "sgst_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoices" ALTER COLUMN "igst_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoices" ALTER COLUMN "cess_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "invoices" ALTER COLUMN "total_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "liabilities" ALTER COLUMN "original_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "liabilities" ALTER COLUMN "current_balance" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "liabilities" ALTER COLUMN "monthly_emi" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "liabilities" ALTER COLUMN "total_paid_so_far" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "liabilities" ALTER COLUMN "collateral_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "loan_amortization" ALTER COLUMN "opening_balance" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "loan_amortization" ALTER COLUMN "emi" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "loan_amortization" ALTER COLUMN "principal" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "loan_amortization" ALTER COLUMN "interest" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "loan_amortization" ALTER COLUMN "closing_balance" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "mutual_funds" ALTER COLUMN "nav" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "mutual_funds" ALTER COLUMN "total_investment" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "mutual_funds" ALTER COLUMN "current_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "mutual_funds" ALTER COLUMN "gain_loss" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "nps_accounts" ALTER COLUMN "equity_fund_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "nps_accounts" ALTER COLUMN "debt_fund_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "nps_accounts" ALTER COLUMN "alternative_fund_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "nps_accounts" ALTER COLUMN "total_value" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "nps_accounts" ALTER COLUMN "total_contributed" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "nps_accounts" ALTER COLUMN "employer_contribution" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "nps_accounts" ALTER COLUMN "gain_loss" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "other_sources_income" ALTER COLUMN "amount_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "price_snapshots" ALTER COLUMN "price" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "price_snapshots" ALTER COLUMN "day_high" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "price_snapshots" ALTER COLUMN "day_low" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "price_snapshots" ALTER COLUMN "previous_close" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "price_snapshots" ALTER COLUMN "change" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "projection_entries" ALTER COLUMN "amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "provident_fund" ALTER COLUMN "employee_balance" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "provident_fund" ALTER COLUMN "employer_balance" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "provident_fund" ALTER COLUMN "interest_balance" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "provident_fund" ALTER COLUMN "total_balance" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "provident_fund" ALTER COLUMN "total_contributed" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "provident_fund" ALTER COLUMN "interest_earned" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "purchase_invoices" ALTER COLUMN "taxable_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "purchase_invoices" ALTER COLUMN "cgst_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "purchase_invoices" ALTER COLUMN "sgst_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "purchase_invoices" ALTER COLUMN "igst_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "purchase_invoices" ALTER COLUMN "cess_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "purchase_invoices" ALTER COLUMN "total_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "real_estate" ALTER COLUMN "purchase_price" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "real_estate" ALTER COLUMN "current_valuation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "real_estate" ALTER COLUMN "gain_loss" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "real_estate" ALTER COLUMN "mortgage_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "real_estate" ALTER COLUMN "monthly_rent" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "real_estate" ALTER COLUMN "property_tax_annual" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "recurring_expenses" ALTER COLUMN "amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "retirement_asset_selection" ALTER COLUMN "sale_price_override_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "retirement_asset_selection" ALTER COLUMN "expected_future_rent_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "salary_income" ALTER COLUMN "gross_salary_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "salary_income" ALTER COLUMN "exemptions_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "salary_income" ALTER COLUMN "section16_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "salary_income" ALTER COLUMN "taxable_salary_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "salary_income" ALTER COLUMN "tds_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sips" ALTER COLUMN "starting_nav" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sips" ALTER COLUMN "monthly_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sips" ALTER COLUMN "total_invested_so_far" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_deductions" ALTER COLUMN "deductible_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_deductions" ALTER COLUMN "available_limit" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_deductions" ALTER COLUMN "utilizable_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_deductions" ALTER COLUMN "claimed_amount" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_deductions" ALTER COLUMN "amount_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_payments" ALTER COLUMN "cgst_liability" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_payments" ALTER COLUMN "sgst_liability" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_payments" ALTER COLUMN "igst_liability" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_payments" ALTER COLUMN "cess_liability" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_payments" ALTER COLUMN "cgst_itc_utilized" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_payments" ALTER COLUMN "sgst_itc_utilized" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_payments" ALTER COLUMN "igst_itc_utilized" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_payments" ALTER COLUMN "cgst_cash_paid" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_payments" ALTER COLUMN "sgst_cash_paid" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_payments" ALTER COLUMN "igst_cash_paid" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tax_payments" ALTER COLUMN "cess_cash_paid" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tds_credits" ALTER COLUMN "income_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "tds_credits" ALTER COLUMN "tds_paisa" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "equity_target" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "equity_allocation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "equity_actual" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "mf_target" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "mf_allocation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "mf_actual" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "gold_target" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "gold_allocation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "gold_actual" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "nps_target" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "nps_allocation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "nps_actual" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "pf_target" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "pf_allocation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "pf_actual" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "re_target" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "re_allocation" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "re_actual" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "emergency_target" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "emergency_actual" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "deduction_target" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "deduction_actual" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "total_planned_investment" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "yearly_investment_plan" ALTER COLUMN "total_actual_investment" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "fy_close_status" ADD COLUMN "locked_by" text;