// AUTO-GENERATED by scripts/compute-schema-hash.mjs — DO NOT EDIT BY HAND.
// Regenerated on every `npm run build` via the prebuild hook.
// Source: src/db/schema.ts (sha256 of file contents).
export const SCHEMA_HASH = 'sha256:e9495d7c221cc4b590e63d182a94e410257d970c7605cf84df7e0f62ac2ae028';
