// AUTO-GENERATED by scripts/compute-schema-hash.mjs — DO NOT EDIT BY HAND.
// Regenerated on every `npm run build` via the prebuild hook.
// Source: src/db/schema.ts (sha256 of file contents).
export const SCHEMA_HASH = 'sha256:7d811bcee0db2bf52bb2409f571a75e7f699e40eaae708fb464d7e083716827b';
