// AUTO-GENERATED by scripts/compute-schema-hash.mjs — DO NOT EDIT BY HAND.
// Regenerated on every `npm run build` via the prebuild hook.
// Source: src/db/schema.ts (sha256 of file contents).
export const SCHEMA_HASH = 'sha256:21dd8375ea57d7742b453d69f4f5dfbdc13a7739b1e8b6f8425d89906ac96c19';
